version: "3"
services:

  nginx:
    image: nginx:latest
    ports:
      - "7000:7000"
      - "9000:9000"
    volumes:
      - ./conf/app.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - web
      
  web:
    build:
      context: .
      dockerfile: ./conf/app.dockerfile
    image: hello_nginx_web
    command: gunicorn -w 4 -b 0.0.0.0:7001 --chdir ./web app1:app
    ports:
      - "7001:7001"
      
  web2:
    image: hello_nginx_web
    command: gunicorn -w 4 -b 0.0.0.0:7002 --chdir ./web app2:app
    ports:
      - "7002:7002"
    depends_on:
      - web

  web3:
    image: hello_nginx_web
    command: gunicorn -w 4 -b 0.0.0.0:7003 --chdir ./web app3:app
    ports:
      - "7003:7003"
    depends_on:
      - web

  web4:
    image: hello_nginx_web
    command: gunicorn -w 4 -b 0.0.0.0:7004 --chdir ./web app4:app
    ports:
      - "7004:7004"
    depends_on:
      - web